title: RESTful API v jazyce Python
authorGN: Miroslav
authorFN: Hrončok
authorWithDegrees: Bc. Miroslav Hrončok
supervisor: Ing. Jakub Jirůtka
keywordsCS: web, API, REST, RESTful, Python, HATEOAS
keywordsEN: web, API, REST, RESTful, Python, HATEOAS
department: Katedra softwarového inženýrství
placeForDeclarationOfAuthenticity: V~Praze
declarationOfAuthenticityOption: 4
